development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: prelaunchr_development
  username: postgres
  password: 'ls54Q123'

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: prelaunchr_test
  username: postgres
  password: 'ls54Q123'

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: liveseasonal
  username: postgres
  password: 'ls54Q123'
