default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: prelaunchr_development

test:
  <<: *default
  database: prelaunchr_test

production:
  <<: *default
  database: liveseasonal
  username: postgres
  password: 'ls54Q123'
