development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: prelaunchr_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: prelaunchr_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: liveseasonal
  username: postgres
  password: 'ls54Q123'
